package quadlet

import (
	"fmt"
	"strings"

	"github.com/allod-project/allod/internal/manifest"
)

// GenerateResult holds one or more generated Quadlet unit files for a module.
type GenerateResult struct {
	// Files maps filename (e.g. "photos.container") to file content.
	Files map[string]string
	// IsNative is true for modules that run on the host without a container image.
	IsNative bool
}

// Generate produces the Quadlet unit files for a module.
// For multi-image modules it generates one .container per image.
// For native modules (no images) it generates a .service unit instead.
func Generate(modID string, m *manifest.Manifest, levelName string) (*GenerateResult, error) {
	if levelName == "off" {
		return &GenerateResult{Files: map[string]string{}}, nil
	}

	level, exists := m.Levels[levelName]
	if !exists {
		return nil, fmt.Errorf("level %s not found in manifest for %s", levelName, modID)
	}

	result := &GenerateResult{Files: make(map[string]string)}

	if len(m.Images) == 0 {
		// Native module: generate a .service unit instead of .container
		result.IsNative = true
		content := generateService(modID, m, level)
		result.Files[modID+".service"] = content
		return result, nil
	}

	if len(m.Images) == 1 {
		// Single-image module: generate one .container with ports
		content := generateContainer(modID, m, m.Images[0], level, true)
		result.Files[modID+".container"] = content
		return result, nil
	}

	// Multi-image module: generate one .container per image
	for i, img := range m.Images {
		isPrimary := (i == 0)
		suffix := ""
		if !isPrimary {
			parts := strings.Split(img.Ref, "/")
			shortName := parts[len(parts)-1]
			suffix = "-" + shortName
		}
		filename := modID + suffix + ".container"
		content := generateContainer(modID+suffix, m, img, level, isPrimary)
		result.Files[filename] = content
	}

	return result, nil
}

func generateContainer(unitName string, m *manifest.Manifest, img manifest.Image, level manifest.Level, isPrimary bool) string {
	var sb strings.Builder

	sb.WriteString(fmt.Sprintf("# Generated by allod for unit: %s\n", unitName))
	sb.WriteString("[Unit]\n")
	sb.WriteString(fmt.Sprintf("Description=Allod Module: %s\n", unitName))
	sb.WriteString("After=network-online.target\n\n")

	sb.WriteString("[Container]\n")
	sb.WriteString(fmt.Sprintf("Image=%s:%s\n", img.Ref, img.Tag))
	if len(img.Args) > 0 {
		sb.WriteString(fmt.Sprintf("Exec=%s\n", strings.Join(img.Args, " ")))
	}

	// Only publish host ports on the primary container of the module
	if isPrimary {
		for _, p := range m.Ports {
			cPort := p.N
			if p.ContainerPort > 0 {
				cPort = p.ContainerPort
			}
			sb.WriteString(fmt.Sprintf("PublishPort=%d:%d\n", p.N, cPort))
		}
	}

	if m.Privileges.Userns == "host" {
		sb.WriteString("UserNS=host\n")
	}
	for _, cap := range m.Privileges.Caps {
		sb.WriteString(fmt.Sprintf("AddCapability=%s\n", cap))
	}

	sb.WriteString("\n[Service]\n")
	sb.WriteString("Restart=on-failure\n")
	if level.RAMMB > 0 {
		sb.WriteString(fmt.Sprintf("MemoryMax=%dM\n", level.RAMMB))
	}

	sb.WriteString("\n[Install]\n")
	sb.WriteString("WantedBy=default.target\n")

	return sb.String()
}

func generateService(modID string, m *manifest.Manifest, level manifest.Level) string {
	var sb strings.Builder

	sb.WriteString(fmt.Sprintf("# Generated by allod for native module: %s\n", modID))
	sb.WriteString("[Unit]\n")
	sb.WriteString(fmt.Sprintf("Description=Allod Native Module: %s\n", modID))
	sb.WriteString("After=network-online.target\n\n")

	sb.WriteString("[Service]\n")
	sb.WriteString("Type=oneshot\n")
	sb.WriteString("RemainAfterExit=yes\n")
	sb.WriteString(fmt.Sprintf("# Native module: managed by allod-core, no container image\n"))
	sb.WriteString("Restart=on-failure\n")
	if level.RAMMB > 0 {
		sb.WriteString(fmt.Sprintf("MemoryMax=%dM\n", level.RAMMB))
	}

	sb.WriteString("\n[Install]\n")
	sb.WriteString("WantedBy=default.target\n")

	return sb.String()
}

// GenerateContainer is the legacy single-file API kept for backward compatibility.
func GenerateContainer(modID string, m *manifest.Manifest, levelName string) (string, error) {
	res, err := Generate(modID, m, levelName)
	if err != nil {
		return "", err
	}
	for _, content := range res.Files {
		return content, nil
	}
	return "", nil
}
